version: "3.9"

services:
  db:
    image: mariadb:10.11
    container_name: recepcao_db
    environment:
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: recepcao_api
    build:
      context: ./api-recepcao
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      APPLICATION_PORT: ${APPLICATION_PORT}
      SECRET_KEY_JWT: ${SECRET_KEY_JWT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_KEY: ${DATABASE_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_EMAIL: ${SECRET_EMAIL}
      SECRET_PASSWORD: ${SECRET_PASSWORD}
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: recepcao_frontend
    build:
      context: ./web-admin
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "81:80"
    depends_on:
      - api
    environment:
      NODE_ENV: ${NODE_ENV}

volumes:
  db_data:
