services:
  api:
    build:
      context: ./api-recepcao
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  frontend:
    build:
      context: ./web-admin
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - api
    env_file:
      - .env
