services:
  api:
    build:
      context: ./api-recepcao
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./web-admin
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - api
