version: "3.9"

services:
  db:
    image: mariadb:10.11
    container_name: recepcao_db
    environment:
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_KEY}
      MARIADB_ROOT_PASSWORD: ${DATABASE_KEY}
      MARIADB_DATABASE: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - dokploy-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: recepcao_api
    build:
      context: ./api-recepcao
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'production'
      APPLICATION_PORT: 3000
      SECRET_KEY_JWT: ${SECRET_KEY_JWT}
      
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_KEY: ${DATABASE_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: recepcao_db
      DATABASE_URL: mariadb://${DATABASE_USER}:${DATABASE_KEY}@db:3306/${DATABASE_NAME}

      MAIL_ADRESS: ${MAIL_ADRESS}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SECURE: ${MAIL_SECURE}

      CORS_ORIGIN: ${CORS_ORIGIN}

      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_CPF: ${ADMIN_CPF}
    expose:
      - 3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dokploy-network

  frontend:
    container_name: recepcao_frontend
    build:
      context: ./web-admin
      dockerfile: Dockerfile
      args:
        VITE_API_URL: 'recepcao_api:3000'
    expose:
      - 80
    depends_on:
      - api
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - dokploy-network
 

networks:
  dokploy-network:
    external: true
volumes:
  db_data:
